POST http://localhost:3001/api/like
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmODQ0MzExNWFkNmJmMGE3ZjUwZmVjMCIsIm5hbWUiOiJtaWNoYWVsIiwiY29sb3IiOiIjMDAwIiwiaWF0IjoxNjAyNTAzNDQxfQ.scyYsmp26xoJaY6JZGI6sgcyBHL_Ten42uhTaxrKdP4",
    "_id": "5f84446ba1680d0ada6d736c"
}