POST http://localhost:3001/api/posts
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmODFmYzlmMGZiMjA4MGNlODVlMDE2MCIsIm5hbWUiOiJtaWNoYWVsIiwiY29sb3IiOiJibGFjayIsImlhdCI6MTYwMjM1NDMzNX0.4YwDnilbnx4cPWcfp2miwNMSngBiKDXf1C_Y6OLCBRQ",
    "payload": "second post by me"
}